version: "3.7"

services:

  app:
    container_name: notes-bot
    build: ./
    image: notes-bot:latest
    read_only: true
    environment:
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
