version: "3.7"

services:

  webhook:
    container_name: webhook
    build: ./webhook
    image: webhook:latest
    #read_only: true
    environment:
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
